name: F3Name
main: ua.coolboy.f3name.bukkit.F3NameBukkit
version: ${f3name.version}
author: Cool_boy
folia-supported: true
api-version: 1.21.8
softdepend: [PlaceholderAPI, LuckPerms]
commands:
  f3name:
    aliases: [fname, f3namebukkit, debugname, f3n]
    permission: f3name.reload
