on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    branches:
    - "main"

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: s4u/setup-maven-action@3
      - name: Run build with Maven Wrapper
        run: ./mvn clean package